using System.Net;using System.Net.Http;using System.Security.Cryptography;using System.Text;using System.Text.Json;
namespace FoxESSMonitor;
public sealed class FoxApiClient(AppConfig config,string apiKey){static readonly HttpClient Http=new(){Timeout=TimeSpan.FromSeconds(15)}; public async Task CheckConnectionAsync(CancellationToken ct){var root=config.Endpoint.TrimEnd('/');_ = await Get(root,"/op/v1/device/detail?sn="+Uri.EscapeDataString(config.SerialNumber),ct);} public async Task<EnergySnapshot> ReadAsync(CancellationToken ct){var root=config.Endpoint.TrimEnd('/');var rt=await Post(root,"/op/v1/device/real/query",new{sns=new[]{config.SerialNumber}},ct);var snap=new EnergySnapshot();var result=rt.RootElement.GetProperty("result");var item=result.ValueKind==JsonValueKind.Array?result.EnumerateArray().FirstOrDefault():result;var d=item.ValueKind==JsonValueKind.Object&&item.TryGetProperty("datas",out var ds)?ds:default;if(d.ValueKind==JsonValueKind.Array){var map=d.EnumerateArray().Where(x=>x.TryGetProperty("variable",out _)).ToDictionary(x=>x.GetProperty("variable").GetString()??"",x=>Number(x,"value"),StringComparer.OrdinalIgnoreCase);snap.Pv=Get(map,"pvPower");snap.Pv1=Get(map,"pv1Power");snap.Pv2=Get(map,"pv2Power");snap.Load=First(map,"loadsPower","loadPower","totalLoadsPower");snap.Import=First(map,"gridConsumptionPower","gridPower");snap.Export=Get(map,"feedinPower");snap.Soc=First(map,"SoC","soc");snap.Temperature=First(map,"invTemp","ambientTemp","temperature");var t=d.EnumerateArray().Select(x=>x.TryGetProperty("time",out var v)?v.GetString():null).FirstOrDefault(x=>!string.IsNullOrEmpty(x));snap.Updated=t??DateTime.Now.ToString("g");}
 try{var g=await Get(root,"/op/v0/device/generation?sn="+Uri.EscapeDataString(config.SerialNumber),ct);if(g.RootElement.TryGetProperty("result",out var gr)&&gr.TryGetProperty("today",out var today))snap.TodayKwh=Num(today);}catch{}
 try{var de=await Get(root,"/op/v1/device/detail?sn="+Uri.EscapeDataString(config.SerialNumber),ct);if(de.RootElement.TryGetProperty("result",out var dr)&&dr.TryGetProperty("status",out var st))snap.Status=st.GetInt32() switch{1=>"Online",2=>"Falha",3=>"Offline",_=>st.ToString()};}catch{snap.Status="Online";}
 if(snap.Load is null&&snap.Pv is not null)snap.Load=Math.Max(0,snap.Pv.GetValueOrDefault()+snap.Import.GetValueOrDefault()-snap.Export.GetValueOrDefault());return snap;}
 async Task<JsonDocument> Post(string root,string path,object body,CancellationToken ct){using var req=new HttpRequestMessage(HttpMethod.Post,root+path){Content=new StringContent(JsonSerializer.Serialize(body),Encoding.UTF8,"application/json")};Sign(req,path);return await Send(req,ct);}
 async Task<JsonDocument> Get(string root,string path,CancellationToken ct){using var req=new HttpRequestMessage(HttpMethod.Get,root+path){Content=new ByteArrayContent(Array.Empty<byte>())};req.Content.Headers.ContentType=new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");var pathOnly=path.Split('?')[0];Sign(req,pathOnly);return await Send(req,ct);}
 void Sign(HttpRequestMessage req,string path){var stamp=DateTimeOffset.UtcNow.ToUnixTimeMilliseconds().ToString();var raw=$"{path}\r\n{apiKey}\r\n{stamp}";var sig=Convert.ToHexString(MD5.HashData(Encoding.UTF8.GetBytes(raw))).ToLowerInvariant();req.Headers.TryAddWithoutValidation("token",apiKey);req.Headers.TryAddWithoutValidation("timestamp",stamp);req.Headers.TryAddWithoutValidation("signature",sig);req.Headers.TryAddWithoutValidation("lang","en");req.Headers.TryAddWithoutValidation("User-Agent","FoxESS-Monitor/1.0 (Windows)");}
 static async Task<JsonDocument> Send(HttpRequestMessage req,CancellationToken ct){using var res=await Http.SendAsync(req,ct);if(res.StatusCode==HttpStatusCode.TooManyRequests)throw new Exception("FoxESS: limite de pedidos atingido. Aguarde antes de tentar de novo.");if(!res.IsSuccessStatusCode){var path=req.RequestUri?.AbsolutePath??"/";var status=(int)res.StatusCode;if(status==404)throw new Exception($"Erro de endpoint (HTTP 404 em {path}). O endpoint base deve ser https://www.foxesscloud.com, sem /op/ no fim.");if(status is 401 or 403)throw new Exception($"FoxESS recusou o acesso (HTTP {status}). Confirme a API key e as permissões.");throw new Exception($"FoxESS respondeu HTTP {status} em {path}.");}var doc=JsonDocument.Parse(await res.Content.ReadAsStringAsync(ct));if(doc.RootElement.TryGetProperty("errno",out var e)&&e.GetInt32()!=0)throw new Exception("FoxESS API: "+(doc.RootElement.TryGetProperty("msg",out var m)?m.GetString():$"erro {e}"));return doc;}
 static double? Number(JsonElement o,string name){if(!o.TryGetProperty(name,out var v))return null;return Num(v);}static double? Num(JsonElement v){if(v.ValueKind==JsonValueKind.Number&&v.TryGetDouble(out var d))return d;if(double.TryParse(v.ToString(),System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out d))return d;return null;}static double? Get(Dictionary<string,double?> m,string k)=>m.TryGetValue(k,out var v)?v:null;static double? First(Dictionary<string,double?> m,params string[] keys)=>keys.Select(k=>Get(m,k)).FirstOrDefault(x=>x.HasValue);
}
