using System.Windows;using System.Windows.Input;using System.Windows.Media;using System.Windows.Threading;using Microsoft.Win32;using Forms=System.Windows.Forms;
namespace FoxESSMonitor;
public partial class MainWindow:Window{
 AppConfig cfg;readonly DispatcherTimer timer=new();Forms.NotifyIcon tray;System.Drawing.Icon? appIcon;
 public MainWindow(){InitializeComponent();cfg=ConfigStore.Load();Topmost=cfg.AlwaysOnTop;SetStartup(cfg.StartWithWindows);var iconResource=System.Windows.Application.GetResourceStream(new Uri("pack://application:,,,/Assets/foxess.ico",UriKind.Absolute));if(iconResource is not null){using(iconResource.Stream)appIcon=new System.Drawing.Icon(iconResource.Stream);}tray=new Forms.NotifyIcon{Text="FoxESS Monitor",Icon=appIcon??System.Drawing.SystemIcons.Information,Visible=true};var menu=new Forms.ContextMenuStrip();menu.Items.Add("Abrir",null,(_,_)=>ShowFromTray());menu.Items.Add("Atualizar agora",null,async(_,_)=>await RefreshData());menu.Items.Add("Configuração",null,(_,_)=>Settings());menu.Items.Add("Sair",null,(_,_)=>ExitApp());tray.ContextMenuStrip=menu;tray.DoubleClick+=(_,_)=>ShowFromTray();StateChanged+=(_,_)=>{if(WindowState==WindowState.Minimized)Hide();};timer.Interval=TimeSpan.FromMinutes(Math.Clamp(cfg.RefreshMinutes,1,60));timer.Tick+=async(_,_)=>await RefreshData();timer.Start();Loaded+=async(_,_)=>{if(cfg.DemoMode)ApplyDemo();else await RefreshData();};Closed+=(_,_)=>{timer.Stop();tray.Visible=false;tray.Dispose();appIcon?.Dispose();};}
 void ShowFromTray(){Show();WindowState=WindowState.Normal;Activate();}void ExitApp(){Close();}void MinimizeClick(object s,RoutedEventArgs e)=>Hide();void HeaderDrag(object s,MouseButtonEventArgs e){if(e.ChangedButton!=MouseButton.Left||e.ButtonState!=MouseButtonState.Pressed||e.OriginalSource is not DependencyObject source)return;while(source is not null){if(source is System.Windows.Controls.Primitives.ButtonBase)return;source=VisualTreeHelper.GetParent(source);}try{DragMove();e.Handled=true;}catch(InvalidOperationException){}}async void RefreshClick(object s,RoutedEventArgs e)=>await RefreshData();void SettingsClick(object s,RoutedEventArgs e)=>Settings();
 void Settings(){var w=new SettingsWindow(cfg){Owner=this};if(w.ShowDialog()==true){cfg=w.Result;ConfigStore.Save(cfg);Topmost=cfg.AlwaysOnTop;SetStartup(cfg.StartWithWindows);DemoLabel.Text=cfg.DemoMode?"MODO DEMONSTRAÇÃO":"FOXESS CLOUD";timer.Interval=TimeSpan.FromMinutes(Math.Clamp(cfg.RefreshMinutes,1,60));if(cfg.DemoMode)ApplyDemo();else _=RefreshData();}}
 void SetStartup(bool enabled){try{using var k=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run",true)??Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");if(enabled)k.SetValue("FoxESS Monitor",$"\"{Environment.ProcessPath}\"");else k.DeleteValue("FoxESS Monitor",false);}catch{}}
 void ApplyDemo(){var n=DateTime.Now;PvValue.Text=(3.42+Math.Sin(n.Minute/5d)*.45).ToString("0.00");Pv1Value.Text=$"{(1.71+Math.Sin(n.Minute/6d)*.18):0.00} kW";Pv2Value.Text=$"{(1.71+Math.Cos(n.Minute/7d)*.18):0.00} kW";LoadValue.Text="1.26 kW";GridValue.Text="Exportação 2.16 kW";SocValue.Text="78%";TodayValue.Text="18.7 kWh";StatusValue.Text="Inversor online";StatusDot.Fill=new SolidColorBrush(System.Windows.Media.Color.FromRgb(98,230,178));MetaValue.Text="🌡 31°C   ·   Atualizado agora";DemoLabel.Text="MODO DEMONSTRAÇÃO";ErrorValue.Text="";}
 async Task RefreshData(){if(cfg.DemoMode){ApplyDemo();return;}var key=ConfigStore.Unprotect(cfg.ProtectedApiKey);if(string.IsNullOrWhiteSpace(key)){ErrorValue.Text="Configure a API key nas definições.";AppLog.Write("WARN","Data refresh skipped: API key is not configured.");return;}try{var x=await new FoxApiClient(cfg,key).ReadAsync(CancellationToken.None);if(x.Pv.HasValue)PvValue.Text=x.Pv.Value.ToString("0.00");Pv1Value.Text=Fmt(x.Pv1);Pv2Value.Text=Fmt(x.Pv2);LoadValue.Text=Fmt(x.Load);GridValue.Text=x.Import>0?$"Importação {x.Import:0.00} kW":$"Exportação {x.Export.GetValueOrDefault():0.00} kW";GridValue.Foreground=x.Import>0?System.Windows.Media.Brushes.Orange: new SolidColorBrush(System.Windows.Media.Color.FromRgb(98,230,178));SocValue.Text=x.Soc.HasValue?$"{x.Soc:0}%":"—";TodayValue.Text=x.TodayKwh.HasValue?$"{x.TodayKwh:0.0} kWh":"—";StatusValue.Text="Inversor "+x.Status;StatusDot.Fill=new SolidColorBrush(x.Status=="Online"?System.Windows.Media.Color.FromRgb(98,230,178):System.Windows.Media.Color.FromRgb(255,125,114));MetaValue.Text=$"🌡 {(x.Temperature.HasValue?$"{x.Temperature:0}°C":"—")}   ·   {x.Updated}";DemoLabel.Text="FOXESS CLOUD";ErrorValue.Text="";}catch(Exception ex){AppLog.Write("ERROR","Data refresh failed: "+ex.Message);ErrorValue.Text=ex.Message.Length>105?ex.Message[..105]+"…":ex.Message;}}
 static string Fmt(double? n)=>n.HasValue?$"{n:0.00} kW":"—";
}
