using System.Windows;
namespace FoxESSMonitor;
public partial class SettingsWindow:Window{
 readonly AppConfig original;
 public AppConfig Result{get;private set;}=new();
 public SettingsWindow(AppConfig c){InitializeComponent();original=c;EndpointBox.Text=c.Endpoint;SerialBox.Text=c.SerialNumber;IntervalBox.Text=c.RefreshMinutes.ToString();DemoBox.IsChecked=c.DemoMode;TopBox.IsChecked=c.AlwaysOnTop;StartupBox.IsChecked=c.StartWithWindows;}
 bool TryReadEndpoint(out Uri uri){if(!EndpointNormalizer.TryNormalize(EndpointBox.Text,out uri,out var error)){AppLog.Write("ERROR","Endpoint validation rejected input (invalid HTTPS URL). Endpoint value omitted.");System.Windows.MessageBox.Show(this,"Não consegui interpretar este valor como endereço HTTPS. Confirma o campo Endpoint. (Validador 3)","Endpoint FoxESS · Validador 3",MessageBoxButton.OK,MessageBoxImage.Warning);return false;}EndpointBox.Text=uri.GetLeftPart(UriPartial.Authority);AppLog.Write("INFO",$"Endpoint accepted and normalized to HTTPS host {uri.Host}; URL path/query removed if present.");return true;}
 async void TestClick(object s,RoutedEventArgs e){if(!TryReadEndpoint(out var endpoint))return;var key=string.IsNullOrWhiteSpace(KeyBox.Password)?ConfigStore.Unprotect(original.ProtectedApiKey):KeyBox.Password.Trim();if(string.IsNullOrWhiteSpace(key)){AppLog.Write("WARN","Connection test stopped before network request: API key is not configured. No credential was logged.");System.Windows.MessageBox.Show(this,"Introduza a API key neste ecrã para testar. A chave não será mostrada nem enviada para outro serviço.","Testar ligação",MessageBoxButton.OK,MessageBoxImage.Information);return;}if(string.IsNullOrWhiteSpace(SerialBox.Text)){AppLog.Write("WARN","Connection test stopped before network request: serial number is empty.");System.Windows.MessageBox.Show(this,"Introduza o número de série do inversor.","Testar ligação",MessageBoxButton.OK,MessageBoxImage.Warning);return;}var button=(System.Windows.Controls.Button)s;button.IsEnabled=false;button.Content="A testar…";try{var c=new AppConfig{Endpoint=endpoint.GetLeftPart(UriPartial.Authority),SerialNumber=SerialBox.Text.Trim()};AppLog.Write("INFO",$"Connection test started at {endpoint.Host}/op/v1/device/detail (API key redacted).");await new FoxApiClient(c,key).CheckConnectionAsync(CancellationToken.None);AppLog.Write("INFO","Connection test succeeded; API returned errno 0.");System.Windows.MessageBox.Show(this,"A FoxESS aceitou a ligação e a API key. Pode guardar as definições.","Ligação OK",MessageBoxButton.OK,MessageBoxImage.Information);}catch(Exception ex){AppLog.Write("ERROR","Connection test failed: "+ex.Message);System.Windows.MessageBox.Show(this,ex.Message,"Falha na ligação FoxESS",MessageBoxButton.OK,MessageBoxImage.Error);}finally{button.IsEnabled=true;button.Content="Testar ligação";}}
 void SaveClick(object s,RoutedEventArgs e){if(!TryReadEndpoint(out var u))return;if(!int.TryParse(IntervalBox.Text,out var min)||min<5||min>60){System.Windows.MessageBox.Show(this,"O intervalo deve estar entre 5 e 60 minutos.","FoxESS Monitor",MessageBoxButton.OK,MessageBoxImage.Warning);return;}if(string.IsNullOrWhiteSpace(SerialBox.Text)){System.Windows.MessageBox.Show(this,"Introduza o número de série do inversor.","FoxESS Monitor",MessageBoxButton.OK,MessageBoxImage.Warning);return;}var key=string.IsNullOrWhiteSpace(KeyBox.Password)?original.ProtectedApiKey:ConfigStore.Protect(KeyBox.Password.Trim());Result=new AppConfig{Endpoint=u.GetLeftPart(UriPartial.Authority),SerialNumber=SerialBox.Text.Trim(),ProtectedApiKey=key,RefreshMinutes=min,AlwaysOnTop=TopBox.IsChecked==true,StartWithWindows=StartupBox.IsChecked==true,DemoMode=DemoBox.IsChecked==true};DialogResult=true;}
}
